autocommit complete 1040 (25)

diff --git a/DEVOPS25/lektion7/omdir/first_row b/DEVOPS25/lektion7/omdir/first_row
--- a/DEVOPS25/lektion7/omdir/first_row
+++ b/DEVOPS25/lektion7/omdir/first_row
@@ -7,7 +7,7 @@
 #
 
 if [ "$#" -ne 1 ]; then
-	echo "ERROR: Pass exactly one FILE"
+	echo "ERROR: Pass exactly one FILE" >&2
 fi
 
 echo antal args: $#
