autocommit complete 1042 (06)

diff --git a/DEVOPS25/lektion7/omdir/first_row b/DEVOPS25/lektion7/omdir/first_row
--- a/DEVOPS25/lektion7/omdir/first_row
+++ b/DEVOPS25/lektion7/omdir/first_row
@@ -7,7 +7,7 @@
 #
 
 if [ "$#" -ne 1 ]; then
-	echo "ERROR: Pass exactly one FILE" 2>errors.txt
+	echo "ERROR: Pass exactly one FILE" 1>&2
 fi
 
 echo antal args: $#
