autocommit partial 1041 (05)

diff --git a/ITINF25/lektion8/aterblick/3. redirections/skrivbada b/ITINF25/lektion8/aterblick/3. redirections/skrivbada
--- a/ITINF25/lektion8/aterblick/3. redirections/skrivbada
+++ b/ITINF25/lektion8/aterblick/3. redirections/skrivbada
@@ -2,6 +2,5 @@
 
 echo "Standard output rad 1"
 echo "Standard error rad 1" >&2
-
 echo "Standard output rad 2"
-echo "Standard error rad 1" >&2
+echo "Standard error rad 2" >&2
