autocommit partial 1040 (06)

diff --git a/ITINF25/lektion8/aterblick/3. redirections/skrivbada b/ITINF25/lektion8/aterblick/3. redirections/skrivbada
--- a/ITINF25/lektion8/aterblick/3. redirections/skrivbada
+++ b/ITINF25/lektion8/aterblick/3. redirections/skrivbada
@@ -1,6 +1,6 @@
 #!/bin/bash
 
 echo "Standard output rad 1"
-echo "Standard  rad 1"
+echo "Standard error rad 1" >&2
 
 echo "Standard output rad 2"
