autocommit partial 1040 (48)

diff --git a/ITINF25/lektion8/aterblick/3. redirections/skrivbada b/ITINF25/lektion8/aterblick/3. redirections/skrivbada
--- a/ITINF25/lektion8/aterblick/3. redirections/skrivbada
+++ b/ITINF25/lektion8/aterblick/3. redirections/skrivbada
@@ -4,3 +4,4 @@ echo "Standard output rad 1"
 echo "Standard error rad 1" >&2
 
 echo "Standard output rad 2"
+echo "Standard error rad 1" >&2
